/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package major2;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author avnegers
 */
public class piechart extends javax.swing.JFrame {

    /**
     * Creates new form piechart
     */
    public piechart() {
        initComponents();
        setSize(1300,700);
        setBackground(new Color(150,150,235));
        pp=30;np=70;
        repaint();
    }
    int pp,np;
    String searchTearm;
    public piechart(int pp,int np,String searchTearm) {
        initComponents();
        setSize(1300,700);
        setBackground(new Color(150,150,235));
        this.pp=pp;
        this.np=np;
        this.searchTearm=searchTearm;
    }
    @Override
    public void paint(Graphics g){
        g.clearRect(0, 0, 1376, 760);
        g.setColor(Color.RED);
        g.setFont(new Font(Font.SERIF, 30, 30));
        g.fillArc(200, 150, 500,500, 0, (int)(360*(np/100.0)));
        g.drawString("Negetive Twittes:"+np+"%", 700, 300);
        g.setColor(Color.green);
        g.fillArc(200, 150, 500, 500,  (int)(360*(np/100.0)), 360-(int)(360*(np/100.0)));
        g.setFont(new Font(Font.SERIF, 30, 30));
        g.drawString("Positive Twittes:"+pp+"%", 700, 500);
        g.setFont(new Font(Font.SANS_SERIF,60,60));
        g.setColor(Color.black);
        g.drawString("Twitter Sentiment Analysis Repost For:"+searchTearm, 50, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piechart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
